AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'docker/**/*'
    - 'config/**/*'
    - 'db/*schema.rb'
    - 'db/migrate/*active_storage.rb'
    - 'db/migrate/*active_storage_postgresql.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Metrics/ModuleLength:
  Max: 300

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 11

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
